/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArbitrageExecutor,
  IArbitrageExecutorInterface,
} from "../../../contracts/interfaces/IArbitrageExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    name: "authorizeExecutor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "executeArbitrage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArbitrageExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IArbitrageExecutorInterface {
    return new Interface(_abi) as IArbitrageExecutorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArbitrageExecutor {
    return new Contract(address, _abi, runner) as unknown as IArbitrageExecutor;
  }
}
