/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbitrageExecutorSol from "./ArbitrageExecutor.sol";
export type { arbitrageExecutorSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
